#
#spring:
#  datasource:
#    password: mysqladmin
#    username: root
#    url: jdbc:mysql://192.168.0.123:3306/test?useSSL=false
#    driver-class-name: com.mysql.jdbc.Driver
#  session:
#    store-type: none
#
#fehead:
#  social:
#    qq:
#      app-id:
#      app-secret:
#    filterProcessorUrl: callback.do
#server:
#  port: 8070